-- Generated by CSharp.lua Compiler 1.1.0
-- Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
local System = System
local SystemCollectionsImmutable = System.Collections.Immutable
local MicrosoftCodeAnalysis
System.usingDeclare(function (global) 
  MicrosoftCodeAnalysis = Microsoft.CodeAnalysis
end)
System.namespace("Microsoft.CodeAnalysis", function (namespace) 
  -- <summary>
  -- The base class for representing command line arguments to a
  -- <see cref="CommonCompiler"/>.
  -- </summary>
  namespace.class("CommandLineArguments", function (namespace) 
    local getParseOptions, getCompilationOptions, __init__, __ctor__
    __init__ = function (this) 
      this.PathMap = System.default(SystemCollectionsImmutable.ImmutableArray_1(System.KeyValuePair_2(System.String, System.String)))
      this.ReferencePaths = System.default(SystemCollectionsImmutable.ImmutableArray_1(System.String))
      this.SourcePaths = System.default(SystemCollectionsImmutable.ImmutableArray_1(System.String))
      this.KeyFileSearchPaths = System.default(SystemCollectionsImmutable.ImmutableArray_1(System.String))
      this.Errors = System.default(SystemCollectionsImmutable.ImmutableArray_1(MicrosoftCodeAnalysis.Diagnostic))
      this.MetadataReferences = System.default(SystemCollectionsImmutable.ImmutableArray_1(MicrosoftCodeAnalysis.CommandLineReference))
      this.AnalyzerReferences = System.default(SystemCollectionsImmutable.ImmutableArray_1(MicrosoftCodeAnalysis.CommandLineAnalyzerReference))
      this.AdditionalFiles = System.default(SystemCollectionsImmutable.ImmutableArray_1(MicrosoftCodeAnalysis.CommandLineSourceFile))
      this.EmbeddedFiles = System.default(SystemCollectionsImmutable.ImmutableArray_1(MicrosoftCodeAnalysis.CommandLineSourceFile))
      this.ManifestResources = System.default(SystemCollectionsImmutable.ImmutableArray_1(MicrosoftCodeAnalysis.ResourceDescription))
      this.ScriptArguments = System.default(SystemCollectionsImmutable.ImmutableArray_1(System.String))
      this.SourceFiles = System.default(SystemCollectionsImmutable.ImmutableArray_1(MicrosoftCodeAnalysis.CommandLineSourceFile))
    end
    __ctor__ = function (this) 
      __init__(this)
    end
    getParseOptions = function (this) 
      return this:getParseOptionsCore()
    end
    getCompilationOptions = function (this) 
      return this:getCompilationOptionsCore()
    end
    return {
      IsScriptRunner = false, 
      InteractiveMode = false, 
      Utf8Output = false, 
      EmitPdb = false, 
      ReportAnalyzer = false, 
      DisplayLogo = false, 
      DisplayHelp = false, 
      DisplayVersion = false, 
      DisplayLangVersions = false, 
      NoWin32Manifest = false, 
      ChecksumAlgorithm = 0, 
      PrintFullPaths = false, 
      getParseOptions = getParseOptions, 
      getCompilationOptions = getCompilationOptions, 
      __ctor__ = __ctor__
    }
  end)
end)
