-- Generated by CSharp.lua Compiler 1.1.0
-- Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
local System = System
System.namespace("Microsoft.CodeAnalysis.CSharp", function (namespace) 
  -- <summary>
  -- The command line arguments to a C# <see cref="CSharpCompiler"/>.
  -- </summary>
  namespace.class("CSharpCommandLineArguments", function (namespace) 
    local getParseOptionsCore, getCompilationOptionsCore, __ctor__
    __ctor__ = function (this) 
      this.__base__.__ctor__(this)
    end
    getParseOptionsCore = function (this) 
      return this.ParseOptions
    end
    getCompilationOptionsCore = function (this) 
      return this.CompilationOptions
    end
    return {
      __inherits__ = function (global) 
        return {
          global.Microsoft.CodeAnalysis.CommandLineArguments
        }
      end, 
      getParseOptionsCore = getParseOptionsCore, 
      getCompilationOptionsCore = getCompilationOptionsCore, 
      ShouldIncludeErrorEndLocation = false, 
      __ctor__ = __ctor__
    }
  end)
end)
