-- Generated by CSharp.lua Compiler 1.1.0
-- Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
local System = System
local MicrosoftCodeAnalysisCSharp
System.usingDeclare(function (global) 
  MicrosoftCodeAnalysisCSharp = Microsoft.CodeAnalysis.CSharp
end)
System.namespace("Microsoft.CodeAnalysis.CSharp", function (namespace) 
  namespace.class("MessageProvider", function (namespace) 
    local Instance, GetSeverity, getFTL_InvalidInputFileName, getERR_FileNotFound, __staticCtor__, __ctor__
    __staticCtor__ = function (this) 
      Instance = MicrosoftCodeAnalysisCSharp.MessageProvider()
      this.Instance = Instance
    end
    __ctor__ = function (this) 
      this.__base__.__ctor__(this)
    end
    GetSeverity = function (this, code) 
      return MicrosoftCodeAnalysisCSharp.ErrorFacts.GetSeverity(code)
    end
    getFTL_InvalidInputFileName = function (this) 
      return 2021 --[[(int)ErrorCode.FTL_InvalidInputFileName]]
    end
    getERR_FileNotFound = function (this) 
      return 2001 --[[(int)ErrorCode.ERR_FileNotFound]]
    end
    return {
      __inherits__ = function (global) 
        return {
          global.Microsoft.CodeAnalysis.CommonMessageProvider
        }
      end, 
      GetSeverity = GetSeverity, 
      getFTL_InvalidInputFileName = getFTL_InvalidInputFileName, 
      getERR_FileNotFound = getERR_FileNotFound, 
      __staticCtor__ = __staticCtor__, 
      __ctor__ = __ctor__
    }
  end)
end)
