-- Generated by CSharp.lua Compiler 1.1.0
-- Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
local System = System
System.namespace("Microsoft.CodeAnalysis", function (namespace) 
  -- <summary>
  -- Abstracts the ability to classify and load messages for error codes. Allows the error
  -- infrastructure to be reused between C# and VB.
  -- </summary>
  namespace.class("CommonMessageProvider", function (namespace) 
    return {}
  end)
end)
