-- Generated by CSharp.lua Compiler 1.1.0
local System = System
System.namespace("Microsoft.CodeAnalysis", function (namespace) 
  -- [DebuggerDisplay("{GetDebuggerDisplay(), nq}")]
  -- <summary>
  -- A diagnostic (such as a compiler error or a warning), along with the location where it occurred.
  -- </summary>
  namespace.class("DiagnosticWithInfo", function (namespace) 
    local getDescriptor, getId, getSeverity, getWarningLevel, getIsSuppressed, getLocation, getAdditionalLocations, GetMessage, 
    __ctor__
    __ctor__ = function (this, info, location, isSuppressed) 
      this.__base__.__ctor__(this)
      --Debug.Assert(info != null);
      --Debug.Assert(location != null);
      this._info = info
      this._location = location
      this._isSuppressed = isSuppressed
    end
    getDescriptor = function (this) 
      return System.throw(System.NotImplementedException())
    end
    getId = function (this) 
      return System.throw(System.NotImplementedException())
    end
    getSeverity = function (this) 
      return System.throw(System.NotImplementedException())
    end
    getWarningLevel = function (this) 
      return System.throw(System.NotImplementedException())
    end
    getIsSuppressed = function (this) 
      return System.throw(System.NotImplementedException())
    end
    getLocation = function (this) 
      return System.throw(System.NotImplementedException())
    end
    getAdditionalLocations = function (this) 
      return System.throw(System.NotImplementedException())
    end
    GetMessage = function (this, formatProvider) 
      System.throw(System.NotImplementedException())
    end
    return {
      __inherits__ = function (global) 
        return {
          global.Microsoft.CodeAnalysis.Diagnostic
        }
      end, 
      _isSuppressed = false, 
      getDescriptor = getDescriptor, 
      getId = getId, 
      getSeverity = getSeverity, 
      getWarningLevel = getWarningLevel, 
      getIsSuppressed = getIsSuppressed, 
      getLocation = getLocation, 
      getAdditionalLocations = getAdditionalLocations, 
      GetMessage = GetMessage, 
      __ctor__ = __ctor__
    }
  end)
end)
