-- Generated by CSharp.lua Compiler 1.1.0
-- Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
local System = System
System.namespace("Microsoft.CodeAnalysis", function (namespace) 




  -- <summary>
  -- Values for severity that are used internally by the compiler but are not exposed.
  -- </summary>
  namespace.class("InternalDiagnosticSeverity", function (namespace) 
    return {}
  end)




  -- <summary>
  -- Values for ErrorCode/ERRID that are used internally by the compiler but are not exposed.
  -- </summary>
  namespace.class("InternalErrorCode", function (namespace) 
    return {}
  end)
end)
