-- Generated by CSharp.lua Compiler 1.1.0
local System = System
System.namespace("Microsoft.CodeAnalysis", function (namespace) 
  -- [DebuggerDisplay("{GetDebuggerDisplay(), nq}")]
  -- <summary>
  -- A DiagnosticInfo object has information about a diagnostic, but without any attached location information.
  -- </summary>
  -- <remarks>
  -- More specialized diagnostics with additional information (e.g., ambiguity errors) can derive from this class to
  -- provide access to additional information about the error, such as what symbols were involved in the ambiguity.
  -- </remarks>
  namespace.class("DiagnosticInfo", function (namespace) 
    local __ctor1__, __ctor2__
    __ctor1__ = function (this, messageProvider, errorCode) 
      this._messageProvider = messageProvider
      this._errorCode = errorCode
      this._defaultSeverity = messageProvider:GetSeverity(errorCode)
      this._effectiveSeverity = this._defaultSeverity
    end
    __ctor2__ = function (this, messageProvider, errorCode, arguments) 
      __ctor1__(this, messageProvider, errorCode)
      -- AssertMessageSerializable(arguments);

      this._arguments = arguments
    end
    return {
      _errorCode = 0, 
      _defaultSeverity = 0, 
      _effectiveSeverity = 0, 
      __ctor__ = {
        __ctor1__, 
        __ctor2__
      }
    }
  end)
end)
